executor: slurm

default-resources:
  mem_mb: 10240
  runtime: 30
  cpus_per_task: 1
  slurm_partition: "standard"
  slurm_account: "kouyos.virology.uzh"
  output: "logs/{rule}/{jobid}.out"
  error: "logs/{rule}/{jobid}.err"
  slurm_extra: "'--qos=long --mail-type=BEGIN,END,FAIL --mail-user=tomas.demeter@uzh.ch'"

jobs: 50
printshellcmds: True
rerun-incomplete: True
keep-going: True
keep-incomplete: False
restart-times: 3
use-conda: True
conda-frontend: mamba


set-resources:

#########
# Fastp # 
#########
  fastp:
    cpus_per_task: 64
    mem_mb: max((5000 * attempt), (input.size_mb // 2 * attempt))
    runtime: max((45 * attempt), (input.size_mb // 100 * attempt ))

###########
# Bowtie2 # 
###########
  bowtie2_index: 
    cpus_per_task: 32
    mem_mb: max((10000 * attempt), (input.size_mb * 10 * attempt))
    runtime: max((60 * attempt), (input.size_mb // 1024 * 8 * attempt ))
  
  bowtie2_mapping:
    cpus_per_task: 64
    mem_mb: max((10000 * attempt), (input.size_mb * 1.5 * attempt))
    runtime: max((60 * attempt), (input.size_mb // 80 * attempt ))

##########
# FastQC # 
##########
  FastQC:
    cpus_per_task: 64
    mem_mb: max((15000 * attempt), (input.size_mb * 3 * attempt))
    runtime: max((5 * attempt), (input.size_mb // 1024 * attempt ))

###########
# MultiQC # 
###########
  multiqc:
    cpus_per_task: 1
    mem_mb: 10000 * attempt
    runtime: 5 * attempt

###########
# Kraken2 # 
###########
  kraken2_build_standard_db:
    cpus_per_task: 64
    mem_mb: 30000 * attempt
    runtime: 180 * attempt
  
  kraken2:
    cpus_per_task: 64
    mem_mb: 45000 * attempt
    runtime: 30 * attempt
    
  #kraken2_build_custom_db:
  #  cpus_per_task: 64
  #  mem_mb: max((10000 * attempt), (input.size_mb * 50 * attempt))
  #  runtime: max((2 * attempt), (input.size_mb // 30 * attempt ))

###########
# Bracken # 
###########
  bracken_build_std_db:
    cpus_per_task: 64
    mem_mb: 10000 * attempt
    runtime: 5 * attempt

  #bracken_build_cst_db:
  #  cpus_per_task: 64
  #  mem_mb: 10000 * attempt
  #  runtime: 5 * attempt

#############
# MetaPhlAn # 
#############
  MetaPhlAn4_profiling:
    cpus_per_task: 64
    mem_mb: 40000 * attempt
    runtime: 20 * attempt  

###############
# StrainPhlAn # 
###############
  sample2markers:
    cpus_per_task: 64
    mem_mb: 40000 * attempt
    runtime: 20 * attempt

  StrainPhlAn_get_SGB:
    cpus_per_task: 64
    mem_mb: 40000 * attempt
    runtime: 20 * attempt

  StrainPhlAn_profiling:
    cpus_per_task: 64
    mem_mb: 40000 * attempt
    runtime: 20 * attempt