# directories
result_dir:  ../results/          # should be kept
working_dir: ../inputs/           

# samples to condition
refs:
  samples: ../workflow/metadata/metadata.csv
  adapters: ../inputs/adapters/adapters.fa
  bowtie_index: ../inputs/genomes/human/bowtie_indices/
  bbsuite_index: ../inputs/genomes/human/bbmap_indices
  human_genome: ../inputs/genomes/human/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
  human_genome_dir: ../inputs/genomes/human/
  human_genome_ensembl_link: https://ftp.ensembl.org/pub/release-112/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz

# BBduk
bbduk:
  trim_quality: 10 # 5-10 for resequencing
  mink: 11
  quality_trim: rl
  kmer_trim: r
  kmer_size: 23 # default 23; depends on adapter size
  hdist: 1 # allowed mismatches

  # BBmap
bbmap:
  fast: true
  minid: 0.9
  maxindel: 3
  minhits: 2
  k: 14

# read quality trimming
fastp:
  phread_quality: 30 # Phred+33 score (> 15 for Proton Ion, > 30 or more for Illumina)
  cut_window_size: 4
  cut_mean_quality: 20
  length_required: 50 

MetaPhlAn4_profiling:
  input_type: fastq # use fastq when running for the first time or bowtie2out if rerunning with new metaphlan parameters
  bowtie2db: ../inputs/genomes/metaphlan_bowtie2db/
  index: mpa_vJun23_CHOCOPhlAnSGB_202307
  analysis_type: rel_ab_w_read_stats
  mapq_threshold: 5
  read_min_length: 70
  robust_average: 0.1
  csv_output_merged: ../results/Kraken_Bracken_Metaphlan_output/

kraken2:
  kraken2_db: ../inputs/genomes/kraken2db/
  paired: paired
  confidence: 0.80 
  gzip_compressed: gzip-compressed
  standard_db: ../inputs/genomes/kraken2/kraken2_standard_db/
  standard_db_url: https://genome-idx.s3.amazonaws.com/kraken/k2_standard_20240112.tar.gz
  custom_kraken2_db: ../inputs/genomes/kraken2/kraken2_custom/kraken2_custom_db/
  downloaded_genomes: ../inputs/genomes/kraken2/kraken2_custom/downloaded_genomes/ # where to download genomes from ncbi
  domains: bacteria
  rename_fasta_headers: ../inputs/genomes/kraken2/kraken2_custom/fasta_renamed/
  csv_output_merged: ../results/Kraken_Bracken_Metaphlan_output/

bracken:
  kmer_length: 35 # default 35 for kraken2
  read_length: 100 # default 100
  treshold: 10 # [Default = 10]:: specifies the minimum number of reads required for a classification
  classification_level: 'S' # [Default = 'S', Options = 'D','P','C','O','F','G','S']:: specifies the taxonomic rank to analyze
  output_dir: ../results/Bracken/
  output_dir_bbmap: ../results/Bracken_bbmap/


StrainPhlAn:
  clade: t__SGB17097
  reference_genomes: ../inputs/genomes/strainphlan_genomes/Corynebacterium_accolens/*.bz2
  strainphlan_samples: ["0010009_unknown_Nasal_Nostrilright", "0010020_unknown_Nasal_Nostrilleft"]
  marker_in_n_samples: 0 # how many samples need the marker for the sample to be kept (default 80)
  sample_with_n_markers: 0 # how many samples need to ahve a marker for the amrker to be kept (default 80)
  breadth_thres: 5 # percetage of marker sequence that has to be covered by reads (default 80)
  trim_sequences: 0 # number of bases to trim from the start and end of the marker sequence (default 50)
  
plotting_kraken_metaphlan:
  csv_location: ../results/Kraken_Bracken_Metaphlan_output/
  min_reads: 1
  relative_abundance: 0.0