# directories
result_dir:  ../results/          # should be kept
working_dir: ../inputs/           

# samples to condition
refs:
  bowtie_index: ../inputs/genomes/human/bowtie_indices/
  bbsuite_index: ../inputs/genomes/human/bbmap_indices
  human_genome: ../inputs/genomes/human/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
  samples: ../inputs/raw_reads/metadata.csv
  adapters: ../inputs/adapters/adapters.fa

# BBduk
bbduk:
  threads: 32
  mem_mb: 100000
  trim_quality: 10 # 5-10 for resequencing
  trim_side: r
  kmer_size: 23 # default 23; depends on adapter size
  hdist: 1 # allowed mismatches

  # BBmap
bbmap:
  threads: 32
  mem_mb: 1500000
  fast: true
  minid: 0.9
  maxindel: 3
  minhits: 2
  k: 14

# read quality trimming
fastp:
  threads: 32
  mem_mb: 100000
  phread_quality: 30 # Phred+33 score (> 15 for Proton Ion, > 30 or more for Illumina)
  cut_window_size: 4
  cut_mean_quality: 20
  length_required: 50 

bowtie:
  threads: 32
  mem_mb: 1000000

FastQC:
  installation_dir: /home/tdemet/data/conda/envs/multiqc_env/bin
  threads: 32
  mem_mb: 10000
  
Multiqc:
  mem_mb: 100000

MetaPhlAn4_profiling:
  threads: 32
  mem_mb: 100000
  input_type: fastq # run with "fastq" if running for the first time, otherwise use "bowtie2out" to speed up the mapping
  bowtie2db: ../inputs/genomes/metaphlan_bowtie2db/
  index: mpa_vOct22_CHOCOPhlAnSGB_202212
  analysis_type: rel_ab_w_read_stats
  mapq_threshold: 5
  read_min_length: 70
  robust_average: 0.2

kraken2:
  threads: 32
  mem_mb: 100000
  kraken2_db: ../inputs/genomes/kraken2db/
  paired: paired
  confidence: 0.80
  gzip_compressed: gzip-compressed
  file_format: use-mpa-style
  report_style: both
  standard_db: ../inputs/genomes/kraken2/kraken2_standard_db/
  standard_db_url: https://genome-idx.s3.amazonaws.com/kraken/k2_standard_20240112.tar.gz
  custom_kraken2_db: ../inputs/genomes/kraken2/kraken2_custom/kraken2_custom_db/
  downloaded_genomes: ../inputs/genomes/kraken2/kraken2_custom/downloaded_genomes/ # where to download genomes from ncbi
  domains: bacteria,archaea

StrainPhlAn:
  threads: 32
  mem_mb: 100000
  clade: t__SGB17097
  reference_genomes: ../inputs/genomes/strainphlan_genomes/Corynebacterium_accolens/*.bz2
  strainphlan_samples: ["0010009_unknown_Nasal_Nostrilright", "0010020_unknown_Nasal_Nostrilleft"]
  marker_in_n_samples: 0 # how many samples need the marker for the sample to be kept (default 80)
  sample_with_n_markers: 0 # how many samples need to ahve a marker for the amrker to be kept (default 80)
  breadth_thres: 5 # percetage of marker sequence that has to be covered by reads (default 80)
  trim_sequences: 0 # number of bases to trim from the start and end of the marker sequence (default 50)
  