# directories
result_dir:  ../results/         # should be kept
working_dir: ../inputs/      # can be removed (temporary files)

# samples to condition
refs:
  bowtie_index: ../inputs/genomes/human/bowtie_indices/
  bbsuite_index: ../inputs/genomes/human/bbmap_indices
  human_genome: ../inputs/genomes/human/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
  samples: ../inputs/raw_reads/metadata.csv
  adapters: ../inputs/adapters/adapters.fa

# BBduk
bbduk:
  threads: 14
  mem_mb: 40000
  trim_quality: 10 # 5-10 for resequencing
  trim_side: r
  kmer_size: 23 # default 23; depends on adapter size
  hdist: 1 # allowed mismatches

  # BBmap
bbmap:
  threads: 14
  mem_mb: 40000
  fast: true
  minratio: 0.9
  maxindel: 3
  minhits: 2
  k: 14

# read quality trimming
fastp:
  threads: 14
  mem_mb: 40000
  phread_quality: 20 # Phred+33 score (> 15 for Proton Ion, > 30 or more for Illumina)
  cut_window_size: 4
  cut_mean_quality: 20
  length_required: 50 

bowtie:
  threads: 14
  mem_mb: 40000
